<?php

declare(strict_types=1);

namespace Gebruederheitz\Wordpress\PageOrPostOption;

use Gebruederheitz\Wordpress\MetaFields\MetaForms;
use WP_Post;

class AbstractBooleanPageOrPostOption extends AbstractPageOrPostOption
{
    public function render(WP_Post $post): void
    {
        $this->nonceField->render();
        $checked = $this->getValue($post->ID);
        MetaForms::makeCheckboxField(static::$key)
            ->setChecked($checked)
            ->setLabel(static::$inputLabel)
            ->render();
    }

    /**
     * @param mixed $rawValue
     */
    public static function parseValue($rawValue): bool
    {
        return (bool) $rawValue;
    }

    /**
     * @param ?array<string, mixed> $data
     */
    public function onChange(int $postId, ?array $data): void
    {
        $value = isset($data[static::$key]) && $data[static::$key] === 'on';
        update_post_meta($postId, static::getMetaKey(), $value);
    }

    public static function getValue(int $postId): bool
    {
        return (bool) parent::getValue($postId); // TODO: Change the autogenerated stub
    }
}
